[project]
name = "dotfiles"
version = "0.1.0"
description = "Personal dotfiles manager"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
    "coloredlogs>=15.0.1",
    "pyyaml>=6.0.3",
]
